### ISSUE TITLE
Activity API Error: Parsing JSON

### ISSUE THREAD

**Issue by ulltrium** [co8/happy#12]
Hi Co8,

Great script! I have been using it a lot, as well as the other one, HDS.

However, after the outage this week they must have changed something because none of them work, I get an error: "Activity API Error: Parsing JSON"
I tried to fix it myself but cannot figure out what has changed, I'm not good with python, but for you might be an easy fix.

Thanks for your time!

**Comment by co8** [comment]
Thanks for the kind words! I'll look into the API issues.  I'm not sure yet if it's due to the outage issues, or changes to the API format, or perhaps changes related to POCv11.
